version: '3.8'
services:
  db-dev:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mycon_dev
    ports:
      - '${DB_PORT}:5432'
    networks:
      - backend

  minio:
    image: minio/minio
    container_name: mycon-minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - mycon-minio:/data
    networks:
      - backend

volumes:
  mycon-minio:

networks:
  backend:
